version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      DB_HOST: postgres
      DB_USER: postgres
      DB_PASS: postgres
      DB_SCHEMA: postgres
      DB_DIALECT: postgres
      JWT_SECRET_KEY: super_secret_key
      NODE_ENV: development
      CACHE_HOST: redis
      CACHE_PORT: 6379
      NEW_RELIC_LICENSE_KEY: "$NEW_RELIC_LICENSE_KEY"
      SENDGRID_API_KEY: "$SENDGRID_API_KEY"
    depends_on:
      - postgres
      - redis
    ports:
      - "3000:80"
    volumes:
      - ./app/src:/app/src

  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
    volumes:
      - postgres-volume:/var/lib/postgresql/data

  redis:
    image: "redis:alpine"
    ports:
      - '6379:6379'
    volumes:
      - redis-volume:/var/lib/redis

volumes:
  postgres-volume:
  redis-volume:
