FROM golang:1.17-alpine as builder

WORKDIR /app

COPY go.* ./
RUN ["go", "mod", "download"]

COPY ../cmd ./cmd
COPY .air.toml .

RUN ["apt-get", "update"]
RUN ["apt-get", "install", "make"]

RUN ["make", "install-air"]

ENV PORT=80
EXPOSE 9090
CMD ["make", "run-local"]
