version: "3.8"

services:
  book-app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      DB_HOST: books-postgres
      DB_USER: postgres
      DB_PASS: postgres
      DB_SCHEMA: postgres
      DB_DIALECT: postgres
      NODE_ENV: development
      NEW_RELIC_LICENSE_KEY: "$NEW_RELIC_LICENSE_KEY"
      SENDGRID_API_KEY: "$SENDGRID_API_KEY"
      ORGANIZATION_SERVICE_HOST: 'organization-app'
      RESERVES_SERVICE_HOST: 'reserve-app'
    depends_on:
      - books-postgres
    ports:
      - "3000:80"
    volumes:
      - ./app/src:/app/src

  books-postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '2002:5432'
    volumes:
      - postgres-volume:/var/lib/postgresql/data

volumes:
  postgres-volume:

networks:
  default:
    external: true
    name: micros
