version: "3.8"

services:
  login:
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      DB_HOST: postgres
      DB_USER: postgres
      DB_PASS: postgres
      DB_SCHEMA: postgres
      DB_DIALECT: postgres
      JWT_SECRET_KEY: super_secret_key
      NODE_ENV: development
    depends_on:
      - postgres
    ports:
      - "3000:80"
    volumes:
      - ./app/src:/app/src

  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
    volumes:
      - postgres-volume:/var/lib/postgresql/data

volumes:
  postgres-volume:
