### Create
# @no-log
POST {{base_url}}:{{port}}/books
Content-Type: application/json
organization-name: ORT

{
  "ISBN": "9780140862539",
  "author": "Paul M. Duvall with Steve Matyas, Andrew Glover",
  "title": "Continuous Integration",
  "year": 2010,
  "imagePath": "https://images-na.ssl-images-amazon.com/images/I/51O9tzpYaUL.jpg",
  "totalExamples": 100
}

### Delete
# @no-log
DELETE {{base_url}}:{{port}}/books/9780140862539
organization-name: ORT

### Update
# @no-log
PUT {{base_url}}:{{port}}/books/9780140862539
organization-name: ORT
Content-Type: application/json

{
  "totalExamples": 2,
  "isActive": true
}

### Catalog
# @no-log
GET {{base_url}}:{{port}}/books?searchBy=Gene&limit=3&offset=0
organization-name: ORT

### The 5 most wanted books
# @no-log
GET {{base_url}}:{{port}}/books/most-wanted
organization-name: ORT
