### Create
# @no-log
POST {{base_url}}:{{port}}/books
Content-Type: application/json
auth-token: Bearer {{auth-token}}
api-token: Bearer {{api-token}}

{
  "ISBN": "9780140862539",
  "author": "Paul M. Duvall with Steve Matyas, Andrew Glover",
  "title": "Continuous Integration",
  "year": 2010,
  "imagePath": "https://images-na.ssl-images-amazon.com/images/I/51O9tzpYaUL.jpg",
  "totalExamples": 100
}

### Delete
# @no-log
DELETE {{base_url}}:{{port}}/books/9780140862539
auth-token: Bearer {{auth-token}}
api-token: Bearer {{api-token}}

### Update
# @no-log
PUT {{base_url}}:{{port}}/books/978-1942788003
auth-token: Bearer {{auth-token}}
api-token: Bearer {{api-token}}
Content-Type: application/json

{
  "totalExamples": 100
}

### Catalog
# @no-log
GET {{base_url}}:{{port}}/books?searchBy=Gene&limit=3&offset=0
auth-token: Bearer {{auth-token}}
api-token: Bearer {{api-token}}

# 978-1942788003
# 9780140862539
### Reservation
# @no-log
POST {{base_url}}:{{port}}/books/9780140862539/reservations
auth-token: Bearer {{auth-token}}
api-token: Bearer {{api-token}}
Content-Type: application/json

// YYYY-mm-DD
{
  "reservationDate": "2021-09-19"
}

### Reservations
# @no-log
GET {{base_url}}:{{port}}/books/9780140862539/reservations?dateFrom=2021-10-01&dateTo=2021-10-06&limit=4&offset=0
auth-token: Bearer {{auth-token}}
api-token: Bearer {{api-token}}
Content-Type: application/json

### The 5 most wanted books
# @no-log
GET {{base_url}}:{{port}}/books/most-wanted
auth-token: Bearer {{auth-token}}
api-token: Bearer {{api-token}}
Content-Type: application/json