### Login
# @no-log
POST {{base_url}}:{{port}}/login
Content-Type: application/json

{
  "email": "santi@library.com",
  "password": "secret-pass",
  "organizationName": "Aulas"
}

> {%
  client.global.set('auth-token', response.headers.valueOf('auth-token'));
  client.global.set('api-token', response.headers.valueOf('api-token'))
%}
