### Login
# @no-log
POST {{base_url}}:{{port}}/login
Content-Type: application/json

{
  "email": "some.email@fi365.ort.edu.uy7",
  "password": "ladebw",
  "organizationName": "Aulas85"
}

> {%
  client.global.set('auth-token', response.headers.valueOf('auth-token'));
  client.global.set('api-token', response.headers.valueOf('api-token'))
%}
