### Login Admin
# @no-log
POST {{login_url}}/login
Content-Type: application/json

{
  "email": "admin@ort.com",
  "password": "Password1",
  "organizationName": "ORT"
}

> {%
  client.global.set('auth-token', response.headers.valueOf('auth-token'));
  client.global.set('api-token', response.headers.valueOf('api-token'))
%}

### Login Student
# @no-log
POST {{login_url}}/login
Content-Type: application/json

{
  "email": "alumno@ort.com",
  "password": "Password1",
  "organizationName": "ORT"
}

> {%
  client.global.set('auth-token', response.headers.valueOf('auth-token'));
  client.global.set('api-token', response.headers.valueOf('api-token'))
%}
