### Register
# @no-log
POST {{base_url}}:{{port}}/organizations
Content-Type: application/json

{
  "name": "Test",
  "email": "lorem@ipsumm.cms",
  "password": "dolor_sit_amet",
  "organizationName": "test-organizationn"
}
