### Accept Invitation
// @no-log
POST {{base_url}}:{{port}}/users
Content-Type: application/json
invitation-token: {{invite-token}}

{
  "name": "Santiago Toscanini",
  "password": "ladebw"
}

### Get user active reservations
# @no-log
GET {{base_url}}:{{port}}/users/reservations
auth-token: Bearer {{auth-token}}
