name: NodeJS Continious Integration

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ jenkins-demo ]
jobs:
  test_pull_request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm i
        working-directory: ./app
      - run: npm test -- --coverage
        working-directory: ./app
      - run: npm run clean
        working-directory: ./app
      - run: npm run build
        working-directory: ./app
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: ./app
